services:
  # PostgreSQL Database Service - must be first
  - type: postgres
    name: learnify-db
    plan: free
    
  # Web Service (Backend) 
  - type: web
    name: learnify-backend
    env: python
    buildCommand: |
      apt-get update && 
      apt-get install -y imagemagick && 
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: CORS_ORIGINS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: learnify-db
          property: connectionString
      - key: ADMIN_EMAIL
        value: "admin@example.com"
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: ADMIN_PASSKEY
        generateValue: true
      - key: RENDER
        value: true
    # Run database initialization before starting the web service
    preDeployCommand: python init_db.py 